/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange email and password for a bearer token
         * @description The only browser route that does not require a token. A failed sign-in always answers 401 with the same message whether or not the account exists, so this cannot be used to discover which emails are registered. Repeated failures from one address are rate limited.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example tk@notifyhub.test
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example correct-horse-battery-staple
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email or password is incorrect. Identical for both failure cases. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign it in
         * @description Self sign-up. Answers with the same Session as sign-in. A new account starts on the default channel preferences. Unlike sign-in, a taken email answers 409, because a sign-up form has to be able to say so. Attempts are rate limited per address.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example TK */
                        name?: string;
                        /**
                         * Format: email
                         * @example tk@notifyhub.test
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example correct-horse-battery-staple
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Account created and signed in */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description An account with that email already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user, as the database currently has them
         * @description Re-reads name and email rather than echoing the token, so a renamed account shows its current details on the next page load. Answers 401 if the token is valid but the account behind it is gone.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's notifications */
        get: {
            parameters: {
                query?: {
                    /** @description Pass the nextCursor from the previous page */
                    cursor?: string;
                    limit?: number;
                    status?: "all" | "unread";
                    /** @description Filter to one notification type. An unrecognised value is ignored rather than rejected, so a client sending a type this version does not know about still gets an inbox. */
                    type?: components["schemas"]["NotificationType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Notification"][];
                            /** @example 3 */
                            unreadCount: number;
                            /** @example 2026-09-21T08:14:00.000Z_01J9Z */
                            nextCursor?: string | null;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Badge count only (cheap call for page load) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unread count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 3 */
                            unreadCount: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark one notification as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated notification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notification: components["schemas"]["Notification"];
                            unreadCount: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark every notification as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 3 */
                            updated: number;
                            /** @example 0 */
                            unreadCount: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user's channel preferences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preferences"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /** Replace the signed-in user's channel preferences */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            responses: {
                /** @description Saved preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preferences"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a device token for mobile or browser push */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        platform: "web" | "android" | "ios";
                    };
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Producer endpoint — enqueue a notification
         * @description Called by other parts of the system, never by the browser. Requires the x-service-key header. Returns 202 as soon as the jobs are queued — one per enabled channel, not one for the notification, so that a channel failing cannot stop the others. Send the same idempotencyKey twice and the second call is ignored; the response then carries the notificationId of the call that won.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                        type: components["schemas"]["NotificationType"];
                        /** @example Ada assigned you a task */
                        title: string;
                        /** @example Design review */
                        body?: string;
                        /** @example /tasks/91 */
                        link?: string;
                        /**
                         * @default normal
                         * @enum {string}
                         */
                        priority?: "urgent" | "normal" | "low";
                        /** @example task-91-assigned-u42 */
                        idempotencyKey?: string;
                        /**
                         * Format: date-time
                         * @description Hold the delivery until this moment — reminders and deadline warnings. Takes precedence over the recipient's quiet hours: a reminder set for 09:00 must not be pulled back to 07:00. Must be RFC 3339; anything else is a 400.
                         * @example 2026-10-04T09:00:00.000Z
                         */
                        deliverAt?: string;
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The notification id, which every per-channel job is keyed on. Null when the user has every channel for this type switched off, or when a duplicate was lost a race and the winning key could not be read back. */
                            jobId: string | null;
                            /**
                             * @description queued  — jobs are waiting to be picked up now. delayed — jobs carry a delay, from deliverAt or from the
                             *                recipient's quiet hours.
                             *     duplicate — this idempotency key was already used. suppressed — no channel is enabled for this type.
                             * @enum {string}
                             */
                            status: "queued" | "delayed" | "duplicate" | "suppressed";
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/queue-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The same statistics, for the alert job and the runbook
         * @description Identical body to GET /ops/queue-stats minus the `you` block, and reachable with the service key so a monitor can poll it without a user token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue and delivery statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueStats"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything that gave up, with why
         * @description A job lands here only after all five attempts failed, or immediately on a permanent failure. Nothing removes entries automatically, so this is the evidence for the runbook.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dead-lettered deliveries, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["DeadLetterEntry"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dead-letters/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-queue one dead-lettered delivery
         * @description The manual half of the runbook. Puts the delivery back on its channel's queue with a full set of attempts and removes the dead-letter entry, so a provider outage does not have to be paid for by hand.
         */
        post: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Re-queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "requeued";
                            notificationId: string;
                            /** @enum {string} */
                            channel: "in_app" | "email" | "push";
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/queue-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue depth, failure rate and email quota
         * @description The signed-in view of the system's health. Deliberately not restricted to a staff role: this is a portfolio project with one shared team account, and the value of the view comes from being openable without a second login. It exposes counts, durations and error strings - no user data - so the worst case is that somebody learns how busy the queue is.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue and delivery statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueStats"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NotificationType: "task_assigned" | "payment_received" | "deadline_warning" | "comment" | "system";
        /** @description Never includes passwordHash. There is no field for it and there must never be one - the sign-in handler selects columns explicitly for the same reason. */
        User: {
            /** @example 01J9ZQ8K3N */
            id: string;
            /** Format: email */
            email: string;
            /** @example TK */
            name?: string | null;
        };
        Session: {
            /**
             * @description Bearer token. Expires after 12 hours. There is no refresh flow, so expiry means signing in again - which is why it is not seven days.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token: string;
            user: components["schemas"]["User"];
        };
        QueueStatus: {
            /** @example notifications */
            name: string;
            /** @description Ready to be picked up */
            waiting: number;
            /** @description Being delivered right now */
            active: number;
            /** @description Held for quiet hours, a quota or a reminder */
            delayed: number;
            /** @description Delivered and trimmed after an hour */
            completed: number;
            /** @description Retrying, or dead-lettered once attempts ran out */
            failed: number;
            /** @description A boolean rather than a count: BullMQ's getJobCounts reports no paused state in this version, and an invented number here would be worse than none. A paused queue is the most useful thing to know when notifications stop arriving. */
            paused: boolean;
        };
        DeliveryStats: {
            /** @example 24 */
            windowHours: number;
            sent: number;
            failed: number;
            dead: number;
            /**
             * Format: float
             * @description failed / (sent + failed). Dead letters are excluded: a dead letter is the system correctly giving up, and counting it twice makes the rate look worse than it is.
             * @example 0.0231
             */
            failureRate: number;
            byChannel: {
                [key: string]: {
                    sent: number;
                    failed: number;
                    dead: number;
                };
            };
        };
        /** @description Producer row created to provider accepted it, for successful deliveries in the window. BullMQ's processedOn is deliberately not used: that measures how long the worker held the job, and completed jobs are trimmed after an hour. Percentiles rather than a mean, because a delivery that needed retries waited out the backoff and would drag an average towards the failures already reported above. */
        ProcessingStats: {
            /**
             * @description Null when nothing has been delivered in the window
             * @example 412
             */
            p50Ms: number | null;
            /** @example 8391 */
            p95Ms: number | null;
            /** @description Successful deliveries behind these percentiles */
            samples: number;
        };
        QueueStats: {
            /**
             * @description failing when Redis is unreachable, when the dead-letter queue is at or over DLQ_FAIL_THRESHOLD, or when a quarter of deliveries failed. degraded at half those thresholds, or when more than 500 jobs are waiting.
             * @enum {string}
             */
            status: "ok" | "degraded" | "failing";
            /** Format: date-time */
            checkedAt: string;
            redis: {
                reachable: boolean;
            };
            depth: {
                /** @description Waiting plus delayed, across both queues */
                total: number;
                waiting: number;
                active: number;
                delayed: number;
            };
            queues: {
                notifications: components["schemas"]["QueueStatus"];
                email: components["schemas"]["QueueStatus"];
            };
            deadLetter: {
                size: number;
                /** @example 10 */
                warnThreshold: number;
                /** @example 50 */
                failThreshold: number;
            };
            deliveries: components["schemas"]["DeliveryStats"];
            processing: components["schemas"]["ProcessingStats"];
            emailQuota: {
                /** @description Against the UTC day, which is how Brevo counts */
                used: number;
                /** @example 300 */
                limit: number;
                /** Format: date-time */
                resetsAtUtc: string;
            };
            /** @description Present only on the signed-in route */
            you?: {
                unreadCount: number;
            };
        };
        DeadLetterEntry: {
            /** @description Pass back to requeue */
            id: string;
            /** Format: date-time */
            queuedAt: string;
            notificationId?: string | null;
            userId?: string | null;
            /** @enum {string|null} */
            channel?: "in_app" | "email" | "push" | null;
            /**
             * @description One line, suitable for a log or an alert subject
             * @example retries exhausted
             */
            reason?: string | null;
            /** @description The provider's own message */
            error?: string | null;
            /** @description True when the channel said this will never work, as opposed to running out of retries. Distinguishes "this address is invalid" from "Brevo was briefly down". */
            permanent: boolean;
            /** Format: date-time */
            failedAt?: string | null;
        };
        Notification: {
            /** @example 01J9ZQ8K3N */
            id: string;
            type: components["schemas"]["NotificationType"];
            /** @example Ada assigned you a task */
            title: string;
            /** @example Design review */
            body?: string;
            /** @example /tasks/91 */
            link?: string | null;
            /** @enum {string} */
            priority?: "urgent" | "normal" | "low";
            /** @example false */
            read: boolean;
            /** Format: date-time */
            createdAt: string;
            data?: {
                [key: string]: unknown;
            };
        };
        ChannelSet: {
            inApp: boolean;
            email: boolean;
            push: boolean;
        };
        Preferences: {
            /**
             * @description One ChannelSet per notification type
             * @example {
             *       "task_assigned": {
             *         "inApp": true,
             *         "email": true,
             *         "push": false
             *       },
             *       "payment_received": {
             *         "inApp": true,
             *         "email": true,
             *         "push": true
             *       },
             *       "deadline_warning": {
             *         "inApp": true,
             *         "email": false,
             *         "push": true
             *       },
             *       "comment": {
             *         "inApp": true,
             *         "email": false,
             *         "push": false
             *       },
             *       "system": {
             *         "inApp": true,
             *         "email": true,
             *         "push": false
             *       }
             *     }
             */
            channels: {
                [key: string]: components["schemas"]["ChannelSet"];
            };
            quietHours?: {
                /** @example 22:00 */
                start?: string;
                /** @example 07:00 */
                end?: string;
                /** @example Asia/Bangkok */
                timezone?: string;
            } | null;
        };
        Error: {
            error: {
                /** @example not_found */
                code: string;
                /** @example Notification not found */
                message: string;
            };
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
