/**
 * Types come from the contract, not from this folder.
 *
 * `schema.d.ts` is generated by `npm run api:types` from
 * `contracts/openapi.yaml`, and CI re-runs that generator and fails if the
 * committed file differs. That is the whole point: a hand-written `Notification`
 * interface would drift the first time somebody added a field to the API, and
 * the drift would show up as a runtime bug rather than a compile error.
 *
 * The aliases below exist so call sites read as `Notification` rather than
 * `components["schemas"]["Notification"]`. They are aliases, not copies - a new
 * contract field appears on all of them with no edit here.
 */

import type { components } from "./schema";

export type Notification = components["schemas"]["Notification"];
export type NotificationType = components["schemas"]["NotificationType"];
/** The enum is urgent | normal | low, but `priority` itself is optional. */
export type NotificationPriority = NonNullable<Notification["priority"]>;
export type User = components["schemas"]["User"];
export type Session = components["schemas"]["Session"];
export type Preferences = components["schemas"]["Preferences"];
export type ChannelSet = components["schemas"]["ChannelSet"];
export type QueueStats = components["schemas"]["QueueStats"];

/** The five types the API defines, for filter controls and icon mapping. */
export const NOTIFICATION_TYPES = [
  "task_assigned",
  "payment_received",
  "deadline_warning",
  "comment",
  "system",
] as const satisfies readonly NotificationType[];

/**
 * The list envelope, which the contract defines inline on GET /notifications
 * rather than as a named schema.
 */
export interface NotificationPage {
  items: Notification[];
  unreadCount: number;
  nextCursor?: string | null;
}

/**
 * The API accepts only `all` and `unread`.
 *
 * There is no `read` filter, so the UI offers "All" and "Unread" rather than
 * offering a third option that would 400.
 */
export type NotificationStatusFilter = "all" | "unread";

/**
 * The error codes the API actually returns.
 *
 * A union rather than `string`, so a typo in a comparison is a compile error.
 * `unknown` is the escape hatch: the backend may add a code this client version
 * has never heard of, and a new server should not break an old bundle.
 */
export type ApiErrorCode =
  | "unauthorized"
  | "forbidden"
  | "not_found"
  | "validation_error"
  | "rate_limited"
  | "conflict"
  | "internal_error"
  | "service_unavailable"
  | (string & {});